-- Run once in the Supabase SQL editor used by the portfolio administration panel.
create table if not exists public.portfolio_records (
  key text primary key,
  kind text not null check (kind in ('project', 'site', 'section')),
  data jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.portfolio_records enable row level security;
create index if not exists portfolio_records_kind_order_idx
  on public.portfolio_records (kind, sort_order);

create table if not exists public.portfolio_visitor_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  session_id text,
  visitor_id text,
  event_name text not null,
  path text,
  project_id text,
  referrer text,
  language text,
  timezone text,
  viewport_width integer,
  viewport_height integer,
  device_type text,
  browser text,
  operating_system text,
  utm_source text,
  utm_medium text,
  utm_campaign text
);

alter table public.portfolio_visitor_events enable row level security;
alter table public.portfolio_visitor_events add column if not exists visitor_id text;
create index if not exists portfolio_visitors_occurred_idx
  on public.portfolio_visitor_events (occurred_at desc);
create index if not exists portfolio_visitors_event_idx
  on public.portfolio_visitor_events (event_name);
create index if not exists portfolio_visitors_project_idx
  on public.portfolio_visitor_events (project_id);
create index if not exists portfolio_visitors_visitor_idx
  on public.portfolio_visitor_events (visitor_id, occurred_at desc);

create table if not exists public.portfolio_visitor_labels (
  visitor_id text primary key,
  label text not null check (char_length(label) between 1 and 80),
  updated_at timestamptz not null default now()
);

alter table public.portfolio_visitor_labels enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portfolio-media',
  'portfolio-media',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public portfolio media" on storage.objects;
create policy "Public portfolio media"
on storage.objects for select
using (bucket_id = 'portfolio-media');

-- No public table policies are created. The server uses the service role only
-- after validating the configured administrator account.
