-- Run once in the Supabase SQL editor used by the portfolio administration panel.
create table if not exists public.portfolio_records (
  key text primary key,
  kind text not null check (kind in ('project', 'site', 'section')),
  data jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.portfolio_records enable row level security;
create index if not exists portfolio_records_kind_order_idx
  on public.portfolio_records (kind, sort_order);

create table if not exists public.portfolio_visitor_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  session_id text,
  event_name text not null,
  path text,
  project_id text,
  referrer text,
  language text,
  timezone text,
  viewport_width integer,
  viewport_height integer,
  device_type text,
  browser text,
  operating_system text,
  utm_source text,
  utm_medium text,
  utm_campaign text
);

alter table public.portfolio_visitor_events enable row level security;
create index if not exists portfolio_visitors_occurred_idx
  on public.portfolio_visitor_events (occurred_at desc);
create index if not exists portfolio_visitors_event_idx
  on public.portfolio_visitor_events (event_name);
create index if not exists portfolio_visitors_project_idx
  on public.portfolio_visitor_events (project_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portfolio-media',
  'portfolio-media',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public portfolio media" on storage.objects;
create policy "Public portfolio media"
on storage.objects for select
using (bucket_id = 'portfolio-media');

-- The static site only uses the public anonymous key. Admin permissions are
-- checked by Supabase with this email, never by a secret stored in the browser.
drop policy if exists "Public reads visible portfolio records" on public.portfolio_records;
create policy "Public reads visible portfolio records"
on public.portfolio_records for select
using (is_visible = true);

drop policy if exists "Admin manages portfolio records" on public.portfolio_records;
create policy "Admin manages portfolio records"
on public.portfolio_records for all
using ((auth.jwt() ->> 'email') = 'alimjdandash@gmail.com')
with check ((auth.jwt() ->> 'email') = 'alimjdandash@gmail.com');

drop policy if exists "Public inserts portfolio events" on public.portfolio_visitor_events;
create policy "Public inserts portfolio events"
on public.portfolio_visitor_events for insert
with check (
  event_name in (
    'page_view', 'open_case', 'open_live_product', 'play_project_video',
    'download_project_video', 'download_cv', 'contact_submit'
  )
);

drop policy if exists "Admin reads portfolio events" on public.portfolio_visitor_events;
create policy "Admin reads portfolio events"
on public.portfolio_visitor_events for select
using ((auth.jwt() ->> 'email') = 'alimjdandash@gmail.com');

drop policy if exists "Admin uploads portfolio media" on storage.objects;
create policy "Admin uploads portfolio media"
on storage.objects for insert
with check (
  bucket_id = 'portfolio-media'
  and (auth.jwt() ->> 'email') = 'alimjdandash@gmail.com'
);

drop policy if exists "Admin updates portfolio media" on storage.objects;
create policy "Admin updates portfolio media"
on storage.objects for update
using (
  bucket_id = 'portfolio-media'
  and (auth.jwt() ->> 'email') = 'alimjdandash@gmail.com'
);

drop policy if exists "Admin deletes portfolio media" on storage.objects;
create policy "Admin deletes portfolio media"
on storage.objects for delete
using (
  bucket_id = 'portfolio-media'
  and (auth.jwt() ->> 'email') = 'alimjdandash@gmail.com'
);
